2023-12-14 10:01:18,873 ERROR app MainThread : (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([WinError 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2023-12-14 10:31:04,993 ERROR app MainThread : (pymysql.err.IntegrityError) (1062, "Duplicate entry 'lyhxr@example.com' for key 'ix_user_email'")
[SQL: INSERT INTO user (username, email, password_hash, country, zipcode, city, address, phone, gender, is_active, is_admin, created_at, updated_at) VALUES (%(username)s, %(email)s, %(password_hash)s, %(country)s, %(zipcode)s, %(city)s, %(address)s, %(phone)s, %(gender)s, %(is_active)s, %(is_admin)s, %(created_at)s, %(updated_at)s)]
[parameters: {'username': 'attila', 'email': 'lyhxr@example.com', 'password_hash': 'scrypt:32768:8:1$tNXaOsyye2xVGPEu$3772ecd7fb60841f0b233bd1b4a5e755ec41b91eab8fa7c0ceecae9b966a296d7b842b452eb5c8d052bcbe22d7d45d02b36e9608366007e06f35dfba2a0b137e', 'country': 'United States', 'zipcode': 123, 'city': 'San Francisco', 'address': '12345', 'phone': 'Male', 'gender': True, 'is_active': 1, 'is_admin': 0, 'created_at': datetime.datetime(2023, 12, 14, 10, 31, 4, 843385), 'updated_at': datetime.datetime(2023, 12, 14, 10, 31, 4, 843385)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2023-12-14 11:11:48,171 ERROR app MainThread : (pymysql.err.IntegrityError) (1062, "Duplicate entry 'lyhxr@example.com' for key 'ix_user_email'")
[SQL: INSERT INTO user (username, email, password_hash, country, zipcode, city, address, phone, gender, is_active, is_admin, created_at, updated_at) VALUES (%(username)s, %(email)s, %(password_hash)s, %(country)s, %(zipcode)s, %(city)s, %(address)s, %(phone)s, %(gender)s, %(is_active)s, %(is_admin)s, %(created_at)s, %(updated_at)s)]
[parameters: {'username': 'asd', 'email': 'lyhxr@example.com', 'password_hash': 'scrypt:32768:8:1$zHGBpSIWNaRdsQGY$c21603112c935d8b8224b44e5cf1d20822b891eddd80e83b83d79b827f3b489e10fde7bdf863a13dd217f9193ae1af1887ca625fdd932509ac3e9f939b73699a', 'country': 'United States', 'zipcode': 123, 'city': 'San Francisco', 'address': '12345', 'phone': 'Male', 'gender': True, 'is_active': 1, 'is_admin': 0, 'created_at': datetime.datetime(2023, 12, 14, 11, 11, 48, 41929), 'updated_at': datetime.datetime(2023, 12, 14, 11, 11, 48, 41929)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2023-12-14 11:26:04,798 ERROR app MainThread : argument 'rounds': 'str' object cannot be interpreted as an integer
2023-12-14 13:33:14,417 ERROR app MainThread : 'user_id' is an invalid keyword argument for BankAccount
2023-12-14 13:33:57,492 ERROR app MainThread : 'user_id' is an invalid keyword argument for BankAccount
2023-12-14 13:34:24,142 ERROR app MainThread : SELECT construct or equivalent text() construct expected, got 10.
2023-12-14 13:37:44,705 ERROR app MainThread : SELECT construct or equivalent text() construct expected, got 10.
2023-12-14 13:37:58,913 ERROR app MainThread : SELECT construct or equivalent text() construct expected, got 1.
2023-12-14 13:38:33,921 ERROR app MainThread : SELECT construct or equivalent text() construct expected, got 1.
2023-12-14 13:38:50,071 ERROR app MainThread : SELECT construct or equivalent text() construct expected, got 1.
2023-12-14 13:39:04,384 ERROR app MainThread : SELECT construct or equivalent text() construct expected, got 1.
2023-12-14 13:39:19,341 ERROR app MainThread : SELECT construct or equivalent text() construct expected, got 1.
2023-12-14 13:39:29,630 ERROR app MainThread : SELECT construct or equivalent text() construct expected, got 1.
2023-12-14 13:40:46,853 ERROR app MainThread : Query.filter_by() takes 1 positional argument but 2 were given
2023-12-14 13:40:52,858 ERROR app MainThread : 'NoneType' object has no attribute 'first'
2023-12-14 13:42:31,487 ERROR app MainThread : 'NoneType' object has no attribute 'first'
2023-12-14 14:07:47,108 ERROR app MainThread : can only concatenate str (not "int") to str
2023-12-14 14:48:36,050 ERROR app MainThread : Query.filter_by() takes 1 positional argument but 2 were given
2023-12-14 14:48:54,684 ERROR app MainThread : Query.filter_by() takes 1 positional argument but 2 were given
2023-12-14 14:49:35,504 ERROR app MainThread : 'BankAccount' object has no attribute 'first'
